language: generic

branches:
  only:
    - main

notifications:
  email: false

jobs:
  include:
    - name: Kuka Core
      language: node_js
      node_js: 12
      cache: npm
      env: TARGET=packages/core
    - name: Kuka Serverless
      language: node_js
      node_js: 12
      cache: npm
      env: TARGET=packages/serverless

before_script: echo $TRAVIS_COMMIT_RANGE; echo $TARGET; pwd; ls -la;
script: if .ci/build.sh $TRAVIS_COMMIT_RANGE $TARGET; then echo "Building '$TARGET' ..." && cd $TARGET && scripts/ci.sh; else echo "No changes detected in '$TARGET'; skipping build."; fi
