name: monorepo-release-test
env:
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  GH_TOKEN: ${{secrets.GH_TOKEN}}

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

  workflow_dispatch:


jobs:
  core:
    runs-on: ubuntu-latest
    env:
      TARGET: "packages/core"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: RANGE="$(jq '.before' $GITHUB_EVENT_PATH)..$(jq '.after' $GITHUB_EVENT_PATH)"
      - run: COMMIT_RANGE=$(echo $RANGE | sed 's/\"//') 
      - run: |
          echo $RANGE; echo $COMMIT_RANGE; pwd; ls -la
      - run: |
          if .ci/build.sh $COMMIT_RANGE $TARGET; then echo "Building '$TARGET' ..." && cd $TARGET && scripts/ci.sh; else echo "No changes detected in '$TARGET'; skipping build."; fi

  serverless:
    runs-on: ubuntu-latest
    env:
      TARGET: "packages/serverless"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: RANGE="$(jq '.before' $GITHUB_EVENT_PATH)..$(jq '.after' $GITHUB_EVENT_PATH)"
      - run: COMMIT_RANGE=$(echo $RANGE | sed 's/\"//') 
      - run: |
          echo $RANGE; echo $COMMIT_RANGE; pwd; ls -la
      - run: |
          if .ci/build.sh $COMMIT_RANGE $TARGET; then echo "Building '$TARGET' ..." && cd $TARGET && scripts/ci.sh; else echo "No changes detected in '$TARGET'; skipping build."; fi
