name: monorepo-release-test
env:
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  GH_TOKEN: ${{secrets.GH_TOKEN}}
  COMMIT_RANGE: "${{github.event.before }}..${{github.event.after}}"
  
on:
  push:
    branches: 
      - main

jobs:
  core:
    runs-on: ubuntu-latest
    env:
      TARGET: "packages/core"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: |
          if .ci/build.sh $COMMIT_RANGE $TARGET; then echo "Building '$TARGET' ..." && cd $TARGET && scripts/ci.sh; else echo "No changes detected in '$TARGET'; skipping build."; fi

  serverless:
    runs-on: ubuntu-latest
    env:
      TARGET: "packages/serverless"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: |
          if .ci/build.sh $COMMIT_RANGE $TARGET; then echo "Building '$TARGET' ..." && cd $TARGET && scripts/ci.sh; else echo "No changes detected in '$TARGET'; skipping build."; fi
